trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install and Build'

  - task: Docker@2
    inputs:
      containerRegistry: '<your-docker-service-connection>'
      repository: 'prasad-node-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'
    displayName: 'Build and Push Docker Image'
